### ISSUE TITLE
readme 注意事项修改

### ISSUE THREAD

**Issue by mysterywolf** [liu2guang/Lua2RTT#6]
当开发坏境是MDK时os.date不支持!格式化时间. 原因RTT的armlibc不支持gmtime函数. 待RTT源码处理该问题.  这句话可以去掉了 现在mdk环境下已经支持了

**Comment by liu2guang** [comment]
感谢指出，lua这块还有我这边还有一些东西有更新，比如cjson与lua绑定，curl与lua绑定。但是没有太多时间处理。要不大佬来测测？

**Comment by mysterywolf** [comment]
我不行 我都没用过lua :( 我就能帮你改改readme 你要是没时间改的话 我给你改一会给你提交一个pr

**Comment by liu2guang** [comment]
行，不过多注意下 lua 和 libc 这块的问题，主要是 rtthread 跑的不是完整的 libc，所有部分接口会有些问题。到时候你使用起来有问题在issues再贴贴

**Comment by mysterywolf** [comment]
好，不过我个人认为，lua是起到辅助角色的，他不能像micropython一样有丰富的库，要尽量的精简，用户有需要可以自己添加。我们只要实现lua原版的所有功能即可。lua和micropython的定位不一样，micropython就是要有丰富的库，但是lua就是给c打辅助，这也是lua原作者所强调的。pr已经提交。
